### ISSUE TITLE
e2e tests via GH actions are getting ETIMEDOUT

### ISSUE THREAD

**Issue by klutchell** [balena-os/leviathan#792]
```
leviathan-client-1  | [2022-06-30T15:01:14.170Z][59415ad-e2e]     not ok 1 - Error: connect ETIMEDOUT 35.174.162.110:443
leviathan-client-1  | [2022-06-30T15:01:14.172Z][59415ad-e2e]       ---
leviathan-client-1  |       stack: >
leviathan-client-1  |         new RequestError (node_modules/request-promise-core/lib/errors.js:14:15)
leviathan-client-1  |       
leviathan-client-1  |         Request.plumbing.callback (node_modules/request-promise-core/lib/plumbing.js:87:29)
leviathan-client-1  |       
leviathan-client-1  |         Request.RP$callback [as _callback] (node_modules/request-promise-core/lib/plumbing.js:46:31)
leviathan-client-1  |       
leviathan-client-1  |         self.callback (node_modules/request/request.js:185:22)
leviathan-client-1  |       
leviathan-client-1  |         Request.onRequestError (node_modules/request/request.js:877:8)
leviathan-client-1  |       at:
leviathan-client-1  |         line: 14
leviathan-client-1  |         column: 15
leviathan-client-1  |         file: node_modules/request-promise-core/lib/errors.js
leviathan-client-1  |         constructor: true
leviathan-client-1  |         function: RequestError
leviathan-client-1  |       type: RequestError
leviathan-client-1  |       cause:
leviathan-client-1  |         &a1 !error
leviathan-client-1  |         name: Error
leviathan-client-1  |         message: connect ETIMEDOUT 35.174.162.110:443
leviathan-client-1  |         stack: |-
leviathan-client-1  |           Error: connect ETIMEDOUT 35.174.162.110:443
leviathan-client-1  |               at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
leviathan-client-1  |               at TCPConnectWrap.callbackTrampoline (internal/async_hooks.js:130:17)
leviathan-client-1  |         errno: -110
leviathan-client-1  |         code: ETIMEDOUT
leviathan-client-1  |         syscall: connect
leviathan-client-1  |         address: 35.174.162.110
leviathan-client-1  |         port: 443
leviathan-client-1  |       error: *a1
leviathan-client-1  |       options:
leviathan-client-1  |         uri: https://59415ad60b4841f0cd40f7cf19176554.balena-devices.com/contract
leviathan-client-1  |         json: true
leviathan-client-1  |         method: GET
leviathan-client-1  |         callback: !function |-
leviathan-client-1  |           "RP$callback"
leviathan-client-1  |           function RP$callback(err, response, body) {
leviathan-client-1  |                       plumbing.callback.call(self, err, response, body);
leviathan-client-1  |                   }
leviathan-client-1  |         transform: null
leviathan-client-1  |         simple: true
leviathan-client-1  |         resolveWithFullResponse: false
leviathan-client-1  | [2022-06-30T15:01:14.176Z][59415ad-e2e]         transform2xxOnly: false
leviathan-client-1  |       response: null
leviathan-client-1  |       test: Testbot Diagnostics
leviathan-client-1  |       source: |2
leviathan-client-1  |             if (Error.captureStackTrace) { // required for non-V8 environments
leviathan-client-1  |                 Error.captureStackTrace(this);
leviathan-client-1  |         --------------^
leviathan-client-1  |             }
leviathan-client-1  |       ...
leviathan-client-1  | [2022-06-30T15:01:14.184Z][59415ad-e2e] 
leviathan-client-1  | [2022-06-30T15:01:14.185Z][59415ad-e2e]     1..1
leviathan-client-1  | [2022-06-30T15:01:14.186Z][59415ad-e2e]     # failed 1 test
leviathan-client-1  | [2022-06-30T15:01:14.192Z][59415ad-e2e] not ok 1 - Testbot Diagnostics # time=145166.489ms
```
https://github.com/balena-os/leviathan/runs/7133908493?check_suite_focus=true

**Comment by klutchell** [comment]
Still seeing this sometimes, though less often than before.
